version: 1.0.1.{build}
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: dotnet restore ./ESignSDK.sln
build:
  publish_nuget: true
  verbosity: minimal
test: false