version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: dotnet restore ./src
build:
  publish_nuget: true
  verbosity: minimal
deploy: off